require("jbajic.options")
require("jbajic.keymaps")
require("jbajic.plugins")
require("jbajic.colorscheme")
require("jbajic.lsp")
require("jbajic.telescope")
require("jbajic.treesitter")
require("jbajic.autopairs")
require("jbajic.gitsigns")
require("jbajic.nvim-tree")
require("jbajic.lualine")
require("jbajic.symbols")

