name: Run diff

on:
  push:
    branches:
      - master
  workflow_dispatch:
  pull_request:

jobs:
  run-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 5

      - name: Set base branch
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "BASE_BRANCH=${{ github.base_ref }}" >> $GITHUB_ENV

      - name: Set base branch # what
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          echo "BASE_BRANCH=master" >> $GITHUB_ENV

      - name: Run git diff
        run: |
          echo "getting difference between ${{ env.BASE_BRANCH }} and HEAD"
          git diff -U0 ${{ env.BASE_BRANCH }}... --
