name: Check runner

on:
  push:
  workflow_dispatch:
  pull_request:

jobs:
  check_runner:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get node info
        run: uname -a
